name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make

    - name: set environment variables
      uses: allenevans/set-env@v2.0.0
      with:
        SKIP_CLIPBOARD_TEST: '1'

    - name: Test
      run: make test
